let products = [
    {
        id: 01,
        title: 'Maths',
        location: 'London',
        price: 100,
        image: './Images/maths.png',
        availableInventory: 15,
        rating: 4,
    },
    {
        id: 02,
        title: 'English',
        location: 'Birmingham',
        price: 150,
        image: './Images/english.png',
        availableInventory: 7,
        rating: 3, 
    },
    {
        id: 03,
        title: 'Music',
        location: 'Manchester',
        price: 200,
        image: './Images/music.png',
        availableInventory: 4,
        rating: 3,  
    },
    {
        id: 04,
        title: 'Geography',
        location: 'London',
        price: 350,
        image: './Images/geography.png',
        availableInventory: 2,
        rating: 4, 
    },
    {
        id: 05,
        title: 'Sports',
        location: 'Birmingham',
        price: 125,
        image: './Images/sports.png',
        availableInventory: 13,
        rating: 2,
    },
    {
        id: 06,
        title: 'Gymnastics',
        location: 'Liverpool',
        price: 100,
        image: './Images/gymnastics.png',
        availableInventory: 8,
        rating: 1,
    },
    {
        id: 07,
        title: 'IT',
        location: 'London',
        price: 200,
        image: './Images/it.png',
        availableInventory: 6,
        rating: 5,
    },
    {
        id: 08,
        title: 'Media ',
        location: 'Bristol',
        price: 300,
        image: './Images/media studies.png',
        availableInventory: 2,
        rating: 4,
    },
    {
        id: 09,
        title: 'French',
        location: 'Liverpool',
        price: 190,
        image: './Images/french.png',
        availableInventory: 10,
        rating: 2, 
    },
    {
        id: 10,
        title: 'Italian',
        location: 'Bristol',
        price: 170,
        image: './Images/italian.png',
        availableInventory: 21,
        rating: 2,
    }
]